### ISSUE TITLE
播放时部分素材无法显示

### ISSUE THREAD

**Issue by lloyar** [LancerComet/SVGAPlayer-UWP#1]
如果人物某个部位不动，在播放时这个部位不会显示。

**Comment by LancerComet** [comment]
是有问题，之后我处理一下，谢谢 _(:3」∠ ❀)_

**Comment by lloyar** [comment]
是否有打算移植为 .NET Core 类库呢？我是 Unity 开发者，正打算把你的工作集成到我的项目中去，我想如果能做成 .NET Core 类库，就能很方便的在别的环境调用。

**Comment by LancerComet** [comment]
@lloyar 已经修复

其实只要把使用 UWP 的绘制层剥离掉就可以在 .NET Core 中使用，不过 .NET Core 目前有拿来绘制的地方么？ _(:3」∠ ❀)_

**Comment by lloyar** [comment]
@LancerComet 我想的是只用 C# 做解析，拿到解析后的纹理数据就可以了，具体我先看看吧，十分感谢这么快的反馈啊。

**Comment by LancerComet** [comment]
@lloyar 有问题继续反馈，我先关掉了 _(:3」∠ ❀)_
