### ISSUE TITLE
没有支持WPF

### ISSUE THREAD

**Issue by MichaelOfGH** [LancerComet/SVGAPlayer-UWP#3]
我是个WPF开发者，不懂UWP，希望能加入对WPF的支持

**Comment by LancerComet** [comment]
我对 WPF 支持也不多，其实就是绘制层的问题，解析的逻辑应该是通用的，我最近是真的没什么空，之后研究研究但得好久了（其实 UWP 的这个库没有实现的东西挺多的）

**Comment by MichaelOfGH** [comment]
好的叭,,那我自己研究研究，我这边这两天要用这个来做我们项目里面的礼物，是个挺重要的模块，谢谢回复了

**Comment by LancerComet** [comment]
https://github.com/LancerComet/SVGAPlayer-UWP/tree/master/Svga/SvgaPlayer/Controls
这里面的 UWP 环境替换成 WPF 即可，绘制逻辑平移过去，换成 WPF 绘制对应的钩子

**Comment by MichaelOfGH** [comment]
这个移植过去了，但是绘制这方面我还不大懂，我再研究研究叭，，有个蛋疼的就是WPF里面没有像CanvasAnimatedControl这样方便的控件，好像只能自己写播放逻辑

**Comment by MichaelOfGH** [comment]
啊啊啊啊啊啊,,,老哥你有时间没,,我现在真的没得办法了 , 在WPF里面我找不到CanvasAnimatedControl的替代控件，你有空的话有偿麻烦你帮帮忙行不
